version: '3.7'

services:
  gotify:
    hostname: gotify
    image: gotify/server
    volumes:
      - /mnt/cephfs/gotify:/app/data
    ports:
      # Default HTTP Port
      - 8080:80/tcp
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
    # Set the appropriate timezone for your location from
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, e.g:
      TZ: America/Chicago
      # Set a password to access the web interface.
      GOTIFY_DEFAULTUSER_PASS: ${GOTIFY_DEFAULTUSER_PASS}