version: '3.7'

services:
  gotify:
    hostname: gotify
    image: gotify/server
    volumes:
      - /mnt/cephfs/gotify:/app/data
    ports:
      # Default HTTP Port
      - 8080:80/tcp
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=America/Chicago