version: '3.7'

services:
  gotify:
    hostname: gotify
    image: gotify/server
    volumes:
      - /mnt/cephfs/gotify:/app/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=America/Chicago