version: '3.0'

services:
  pihole:
    hostname: pihole
    image: pihole/pihole
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - ${FTLCONF_webserver_port:-80}:80/tcp
      # Default HTTPs Port. FTL will generate a self-signed certificate
      #- "443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
      # Uncomment to enable unbound access on local server
      #- 5335:5335/tcp
      # Uncomment to enable SSH
      #- 22/tcp 
    environment:
      - TZ=${TZ:-UTC}
      - FTLCONF_webserver_api_password=${FTLCONF_webserver_api_password}
      - FTLCONF_dns_listeningMode=${FTLCONF_dns_listeningMode}
      - FTLCONF_dns_upstreams=${FTLCONF_dns_upstreams}
      - FTLCONF_dns_revServers=${FTLCONF_dns_revServers}
      - FTLCONF_webserver_port=${FTLCONF_webserver_port}
    cap_add:
      - CAP_SYS_TIME
      - CAP_SYS_NICE
      # Recommended but not required (DHCP needs NET_ADMIN)
      # - NET_ADMIN
    networks:
      dns_net:
        ipv4_address: 172.23.0.7
    volumes:
      - /mnt/cephfs/pihole/etc/pihole:/etc/pihole:rw
      - /mnt/cephfs/pihole/etc/dnsmasq.d:/etc/dnsmasq.d:rw
    restart: unless-stopped

  unbound:
    hostname: unbound
    image: mvance/unbound-rpi:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      dns_net:
        ipv4_address: 172.23.0.8
    volumes:
      - /mnt/cephfs/unbound:/opt/unbound/etc/unbound
      - ./unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro
      - ./forward-records.conf:/opt/unbound/etc/unbound/forward-records.conf:ro
      - ./a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro
      - ./srv-records.conf:/opt/unbound/etc/unbound/srv-records.conf:ro
    ports:
      - "5053:53/tcp"
      - "5053:53/udp"
    healthcheck:
      test: ["NONE"]
    restart: unless-stopped

networks:
  dns_net:

    ipam:
      config:
        - subnet: 172.23.0.0/24
  proxy:
    external: true